[package]
name = "v3"
version = "0.1.0"
authors = ["Maxime Mulder <maxime.mulder@viacesi.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.2"
